server:
  port : 8090
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver 
    username: sa
    password: password
logging:
  level:
    org:
      hibernate:
        type: trace